### ISSUE TITLE
'password.php' not found and various warnings

### ISSUE THREAD

**Issue by themightywolfie** [pratimakandel/Mini-basic-Imdb-website#1]
I am facing the following issues:-

`Warning: include(password.php): failed to open stream: No such file or directory in C:\xampp\htdocs\project\php files\index.php on line 16

Warning: include(): Failed opening 'password.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\project\php files\index.php on line 16

Warning: mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\project\php files\index.php on line 23`

Could you please help me fix them? PS:- I renamed the project folder to 'project'

**Comment by pratimakandel** [comment]
Hey, I am so glad that you're trying to set up this project, however this was my college project and the database password included there currently don't exist. I will redo my ReadMe. Sorry! I will try my best to help you set this up. 

1st Step: Install MySQL in your computer https://dev.mysql.com/doc/mysql-getting-started/en/#mysql-getting-started-installing
2nd Step: create a database in your MYSQL
3rd Step: Import all the SQL files present in my repo to your database this command should do it ``` mysql -u username -p database_name < file.sql```
4th Step: Any where in the PHP files you see a database connection code such as 
```
<?php
          include "password.php";
          $servername = "localhost";
          $db = "S19_350_Team_Blue";

          //create connection
          $connection = mysqli_connect($servername, $username, $password, $db);
                                      
	?>          

```

you can remove include "password.php"
Rename the $db to the database you created above where you imported all the SQL files. 
In the create connection section rename $username with your MYSQL username and the $password too.

I hope this works let me know!

**Comment by themightywolfie** [comment]
I fixed all the warnings I was getting :) 👍. However, I found a few bugs you could fix. I will try to create pull-requests after my exams are over. 

 The password.php got fixed. I just created it like you said

In signup.php, your query in line 126,  `$sql_insert = "INSERT INTO user(username,  password)
                                               VALUES (\"" . $name .  "\", \"" . $pass . "\")";` the parameters are in wrong order as well as incomplete. The table 'user' has 3 columns in order 'user_id','password' and 'username'. 
The correct query is `$sql_insert = "INSERT INTO user (user_id, password, username)
                                                VALUES ($result,'$pass','$name')";`

Also in user-review_table.sql, for some reason, the review table was not created when imported so I created a new review_table.sql file

**Comment by pratimakandel** [comment]
Thank you so much for noticing/fixing the errors. Best of luck with your exams. :)
